### ISSUE TITLE
Basic review

### ISSUE THREAD

**Issue by umputun** [dealancer/validate#5]
_as [requested](https://twitter.com/_dealancer/status/1127579705094361090)_

Generally speaking code looks clean enough, make sense and decently covered. Personally I don't like anything dealing with reflection and will try to avoid it, but I can see valid use cases for this thing. 

Some findings/recommendations:
 
1. Lack of go mod support, worth to add
1. Lack of substructs validation. I think this is your #4. Without sub-structs it won't be too useful in most of practical cases
1. I would suggest to remove `utils.go` and move those functions to `validate.go`
1. All of validators (i.e. `validateMin`, `validateMax', etc) seems to be good candidates to implement some common interface or some func type. Such generalization may allow nice things, like dynamic [switch replacement](https://github.com/dealancer/validate/blob/master/validate.go#L62
)
1. Why you even need make? I don't see justification for this thing here.
1. You don't test `validators.go` functions directly, but only via indirect calls. This is a personal preference, and some would argue it is fine and you should test public API only, but I would suggest adding direct tests because your validate* methods are not trivial and can be tested in isolation. If you add dynamic dispatch it can be a single table test. Generally speaking if you touch tricky subjects like reflection, having more tests will only help.
1. Can be useful to emulate some kind of enum for [those string constants](https://github.com/dealancer/validate/blob/master/validate.go#L8). And one more thing -  making them exposed and adding comments will help to make better godoc, i.e. user will see what tags allowed and what they supposed to do.
1. I don't like your minimal comments on public methods, they should serve as documentation for godoc and have more details. Also some examples for godoc will be useful.
1. Readme example for "Unmarshalling YAML/JSON" is sort of confusing. As a user I have no clue what github.com/creasty/defaults is and why this package even mentioned in a such generic/basic use case. Instead of this I'd expect some examples showing validated unmarshaling of json, yaml, xml, etc.
1. Readme should explain better what validation is and why one may want it

**Comment by dealancer** [comment]
@umputun 

Thank you for the review! It is very useful. I can agree to most of it.

Could you explain more on dynamic switches (4) or provide some example? How would I call such functions in this case? Are you talking about getting function name from the map and calling it?

I am using make as am planning to add more tasks such as linting and I saw some other packages are using it, but it may be an over engineering as this can be done is a simple bash script.

**Comment by umputun** [comment]
> Could you explain more on dynamic switches (4) or provide some example? How would I call such functions in this case? Are you talking about getting function name from the map and calling it?

yeah, something like this. I'd make a map like this:

```go
type valFunc func(value reflect.Value, field reflect.StructField, validator string) error

validatorFuncs := map[ValType] valFunc {
 ValMin: validateMin,
 ValMax: validateMax,
 ...
}

for k, v := range validatorFuncs {
   if k == valType {
      return v(.....)
   }
}
```

**Comment by dealancer** [comment]
@umputun again. thank you for the review. I have implemented most of the suggestions.

1. Done.
2. Done. Also added new syntax to dive into complex fields e.g.: `Complex []map[string]*int `empty=false > empty=false [str=email || str=domain] > nil=false > max=100`
}`.
3. Done.
4. Done.
5. Skipped for now.
6. Partially done.
7. Done.
8. Done.
9. Removed this section for now, will later write a blog post.
10. Done.
